### ISSUE TITLE
Hey Thomas, here is the form.

### ISSUE THREAD

**Issue by katz0018** [katz0018/ecommerce-pattern-library#3]
Hey Thomas Ive been trying to make the forms turn only red if you try and submit without adding a required field but I think its not working. Do you think it's okay? I feel a little weird about it because on a form not everything is supposed to be highlighted but everything I included on the different forms are important.

@thomasjbradley

**Comment by thomasjbradley** [comment]
The fix, is that the CSS isn’t right—when you were writing the original CSS you *added new* CSS instead of replacing the CSS. So, delete these lines:

- https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/forms/form.css#L15-L19
- https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/forms/form.css#L40-L44

---

Also some improvements in the forms code: you don’t need the `<!DOCTYPE>`, etc.—only the fields.

Delete all this from all the form HTML files:
- https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/forms/subscribe-email.html#L1-L13
- https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/forms/subscribe-email.html#L27-L29

---

Do you intend to set all the fonts on your whole website to `sans-serif`?
https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/forms/form.css#L1-L3
