### ISSUE TITLE
A little confused

### ISSUE THREAD

**Issue by katz0018** [katz0018/ecommerce-pattern-library#4]
@thomasjbradley

Hey Thomas, 
 Im feeling a little lost on what's happening with my call to action button.
I tried inserting the h1 and h2 text but its turning the text into the button, which is not what im looking for. How much do we need to have done for this week?

**Comment by thomasjbradley** [comment]
There are 3 small typos:

1. `id` on this line should be `if`:
https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/banners/call-to-action.html#L8

2. `include` is missing the final “e” on these two lines:
https://github.com/katz0018/ecommerce-pattern-library/blob/master/_patterns/banners/call-to-action.html#L6-L7

---

The homepage should be completely done this week. But there’s a little bit of grace period because we aren’t handing the project off to other people until next week.
